steps:
    - name: maven:3.8.1-jdk-17
      entrypoint: mvn
      args: ["test"]
    - name: maven:3.8.1-jdk-17
      entrypoint: mvn
      args: [ 'package','-Dmaven.test.skip=true' ]
    - name: "gcr.io/cloud-builders/gcloud"
      entrypoint: mvn
      args: ["app", "deploy"]
timeout: 1600s